---
title: Cipta Media Seluler
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Arsip Cipta Media Seluler,menggunakan Jekyll dan github pages.
keywords: Cipta Media Seluler,CMS,blog,arsip,Jekyll,github,gh-pages
author:
  cms:
    name: Cipta Media Seluler
    desc: Media interaksi dan pembelajaran bersama tentang pemanfaatan teknologi seluler
      untuk perubahan sosial.
    head_img: static/img/landing/Peningkatan_cipta_media.png
    email: email@mail.co.uk
    github: cms
  riou:
    name: Dwi Satria Utama
    desc: Graphic Designer for WMID
    head_img: 
    email: dwi.satria@wikimedia.or.id
    github: riosatria
sections:
- id: tentang
  i18n: nav.tentang
  name: Tentang
  tpl: tentang.html
  css: ''
- id: proyek
  i18n: nav.proyek
  name: Proyek Lama
  tpl: proyek.html
  css: project
- id: blog
  i18n: nav.blog
  name: Blog
  tpl: blog.html
  css: ''
disqus:
  name: nama_disini
  public_key: public_key_disini
ga:
  id: ga_disini
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
